# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-09-21 10:20
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mydpcrm', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ColdLeads',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('custName', models.CharField(blank=True, max_length=250)),
                ('mobile', models.CharField(blank=True, max_length=25)),
                ('alternate_mobile', models.CharField(blank=True, max_length=25)),
                ('email', models.CharField(blank=True, max_length=250)),
                ('address', models.TextField(blank=True, max_length=500)),
                ('area', models.CharField(blank=True, max_length=250)),
                ('city', models.CharField(blank=True, max_length=250)),
                ('zipcode', models.CharField(blank=True, max_length=250)),
                ('state', models.CharField(blank=True, max_length=250)),
                ('plan', models.CharField(blank=True, max_length=100)),
                ('leadStatus', models.CharField(default='Cold', max_length=25)),
                ('leadType', models.CharField(blank=True, max_length=250)),
                ('pointOfContact', models.CharField(blank=True, max_length=250)),
                ('enquiryDate', models.DateTimeField(blank=True)),
                ('coldDate', models.DateTimeField(auto_now=True)),
                ('leadSource', models.CharField(blank=True, max_length=250)),
                ('currentStatus', models.CharField(blank=True, max_length=100)),
                ('latestUpdate', models.TextField(blank=True, max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='InstalledLeads',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('custName', models.CharField(blank=True, max_length=250)),
                ('mobile', models.CharField(blank=True, max_length=25)),
                ('alternate_mobile', models.CharField(blank=True, max_length=25)),
                ('email', models.CharField(blank=True, max_length=250)),
                ('address', models.TextField(blank=True, max_length=500)),
                ('area', models.CharField(blank=True, max_length=250)),
                ('city', models.CharField(blank=True, max_length=250)),
                ('zipcode', models.CharField(blank=True, max_length=250)),
                ('state', models.CharField(blank=True, max_length=250)),
                ('plan', models.CharField(blank=True, max_length=100)),
                ('leadStatus', models.CharField(default='Cold', max_length=25)),
                ('pointOfContact', models.CharField(blank=True, max_length=250)),
                ('installationDate', models.DateTimeField(auto_now=True)),
                ('leadSource', models.CharField(blank=True, max_length=250)),
                ('currentStatus', models.CharField(blank=True, max_length=100)),
                ('purifierId', models.CharField(blank=True, max_length=15)),
                ('technician', models.CharField(blank=True, max_length=250)),
                ('latestUpdate', models.TextField(blank=True, max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='LeadNotes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('leadNotes', models.CharField(blank=True, max_length=1500)),
                ('dateTime', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='NewLeads',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('custName', models.CharField(blank=True, max_length=250)),
                ('mobile', models.CharField(blank=True, max_length=25)),
                ('alternate_mobile', models.CharField(blank=True, max_length=25)),
                ('email', models.CharField(blank=True, max_length=250)),
                ('address', models.TextField(blank=True, max_length=500)),
                ('area', models.CharField(blank=True, max_length=250)),
                ('city', models.CharField(blank=True, max_length=250)),
                ('zipcode', models.CharField(blank=True, max_length=250)),
                ('state', models.CharField(blank=True, max_length=250)),
                ('plan', models.CharField(blank=True, max_length=100)),
                ('leadStatus', models.CharField(default='New', max_length=25)),
                ('leadType', models.CharField(blank=True, max_length=250)),
                ('pointOfContact', models.CharField(blank=True, max_length=250)),
                ('enquiryDate', models.DateTimeField(auto_now=True)),
                ('leadSource', models.CharField(blank=True, max_length=250)),
                ('currentStatus', models.CharField(blank=True, max_length=100)),
                ('latestUpdate', models.TextField(blank=True, max_length=500)),
                ('utm_source', models.CharField(blank=True, max_length=250)),
                ('utm_campaign', models.CharField(blank=True, max_length=250)),
                ('user', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ReferralNotes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notes', models.CharField(max_length=250)),
                ('timestamp', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='ReferralTbl',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
                ('mobile', models.CharField(max_length=25)),
                ('leadSource', models.CharField(max_length=250)),
                ('purifierId', models.CharField(max_length=15)),
                ('enquiryDate', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(max_length=15)),
                ('note', models.TextField(max_length=500)),
                ('user', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ScheduledLeads',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('custName', models.CharField(blank=True, max_length=250)),
                ('mobile', models.CharField(blank=True, max_length=25)),
                ('alternate_mobile', models.CharField(blank=True, max_length=25)),
                ('email', models.CharField(blank=True, max_length=250)),
                ('address', models.TextField(blank=True, max_length=500)),
                ('area', models.CharField(blank=True, max_length=250)),
                ('city', models.CharField(blank=True, max_length=250)),
                ('zipcode', models.CharField(blank=True, max_length=250)),
                ('state', models.CharField(blank=True, max_length=250)),
                ('plan', models.CharField(blank=True, max_length=100)),
                ('leadStatus', models.CharField(default='Cold', max_length=25)),
                ('pointOfContact', models.CharField(blank=True, max_length=250)),
                ('scheduledDate', models.DateTimeField(auto_now=True)),
                ('leadSource', models.CharField(blank=True, max_length=250)),
                ('currentStatus', models.CharField(blank=True, max_length=100)),
                ('purifierId', models.CharField(blank=True, max_length=15)),
                ('latestUpdate', models.TextField(blank=True, max_length=500)),
                ('lead', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mydpcrm.NewLeads')),
                ('user', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='referralnotes',
            name='reflead',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mydpcrm.ReferralTbl'),
        ),
        migrations.AddField(
            model_name='referralnotes',
            name='user',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='leadnotes',
            name='lead',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mydpcrm.NewLeads'),
        ),
        migrations.AddField(
            model_name='leadnotes',
            name='user',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='installedleads',
            name='lead',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mydpcrm.NewLeads'),
        ),
        migrations.AddField(
            model_name='installedleads',
            name='user',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='coldleads',
            name='lead',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mydpcrm.NewLeads'),
        ),
        migrations.AddField(
            model_name='coldleads',
            name='user',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
