# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-09-22 10:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mydpcrm', '0002_auto_20180921_1550'),
    ]

    operations = [
        migrations.AlterField(
            model_name='installedleads',
            name='leadStatus',
            field=models.CharField(default='Installed', max_length=25),
        ),
        migrations.AlterField(
            model_name='scheduledleads',
            name='leadStatus',
            field=models.CharField(default='Scheduled', max_length=25),
        ),
    ]
