# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-09-25 06:58
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mydpcrm', '0003_auto_20180922_1538'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConvertedLeads',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('custName', models.CharField(blank=True, max_length=250)),
                ('mobile', models.CharField(blank=True, max_length=25)),
                ('alternate_mobile', models.CharField(blank=True, max_length=25)),
                ('email', models.CharField(blank=True, max_length=250)),
                ('address', models.TextField(blank=True, max_length=500)),
                ('area', models.CharField(blank=True, max_length=250)),
                ('city', models.CharField(blank=True, max_length=250)),
                ('zipcode', models.CharField(blank=True, max_length=250)),
                ('state', models.CharField(blank=True, max_length=250)),
                ('plan', models.CharField(blank=True, max_length=100)),
                ('leadStatus', models.CharField(default='Converted', max_length=25)),
                ('pointOfContact', models.CharField(blank=True, max_length=250)),
                ('convertedDate', models.DateTimeField(auto_now=True)),
                ('leadSource', models.CharField(blank=True, max_length=250)),
                ('currentStatus', models.CharField(default='Active', max_length=100)),
                ('latestUpdate', models.TextField(blank=True, max_length=500)),
                ('lead', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mydpcrm.NewLeads')),
                ('user', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
